kind: pipeline
type: docker
name: default

steps:
  - name: build-docker-image
    image: docker:20
    commands:
      - sleep 5
      - docker build -t your-local-registry/your-image-name:latest .
      - docker push your-local-registry/your-image-name:latest

trigger:
  event:
    include:
    - push
  branch:
  - main
