kind: pipeline
name: default

steps:
- name: build
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 5 # give docker enough time to start
  - docker ps -a

services:
- name: docker
  image: docker:dind
  privileged: false
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}