kind: pipeline
type: docker
name: default

trigger:
  event:
    include:
    - push
  branch:
  - main

steps:
  - name: build-docker-image
    image: docker:20
    commands:
      - docker build -t drone-ci-learn:latest .
      - docker push drone-ci-learn:latest