kind: pipeline
type: exec
name: default

steps:
  - name: build
    commands:
      - docker build -t localhost:5000/drone-ci-learn:latest .

trigger:
  event:
    include:
    - push
  branch:
  - main
