kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  privileged: true
  settings:
    debug: true
  commands:
    - sleep 5 # give docker enough time to start
    - docker ps -a
  volumes:
    - name: temp
      path: /tmp
